# Automated Linting 

name: "main-workflow"

# follow standard triggers
on: 
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  RULESET_URL: .spectral/adidas.yml

permissions:
  contents: read

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Run OpenAPI Linter
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: "OASFiles/*.json"
      # - name: save-linting-report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: linting-report-${{ github.run_id }}
      #     path: linting-report-${{ github.run_id }}.json
      #     if-no-files-found: error